# Generated by Django 4.1.7 on 2023-03-17 10:31

from django.db import migrations, models
import profileApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='key',
            field=models.CharField(default=profileApp.models.generate_key, max_length=4),
        ),
    ]
