# Generated by Django 4.1.7 on 2023-03-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0005_profile_games_played_profile_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/IMG_0440.jpeg', null=True, upload_to='avatars/'),
        ),
    ]
