# Generated by Django 4.1.7 on 2023-03-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
