# Generated by Django 4.1.7 on 2023-03-29 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileApp', '0008_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
